/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-surface": "#0b1c30",
        "on-background": "#0b1c30",
        "on-primary-fixed": "#001b3f",
        "inverse-primary": "#abc7ff",
        "on-primary": "#ffffff",
        "outline": "#737782",
        "on-secondary-fixed": "#002109",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#0a458c",
        "tertiary-fixed-dim": "#bdc8d3",
        "secondary-fixed-dim": "#3de273",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#10488f",
        "tertiary-container": "#414b54",
        "primary-fixed": "#d7e2ff",
        "on-tertiary-fixed": "#131d25",
        "error-container": "#ffdad6",
        "secondary-container": "#5dfd8a",
        "on-tertiary-container": "#b1bbc6",
        "on-secondary-fixed-variant": "#005322",
        "secondary-fixed": "#66ff8e",
        "surface-dim": "#cbdbf5",
        "surface": "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "on-surface-variant": "#434751",
        "on-tertiary-fixed-variant": "#3e4851",
        "on-secondary": "#ffffff",
        "secondary": "#006d2f",
        "primary-fixed-dim": "#abc7ff",
        "background": "#f8f9ff",
        "on-error-container": "#93000a",
        "surface-variant": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "surface-bright": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#007232",
        "surface-tint": "#2f5ea6",
        "primary": "#00326b",
        "tertiary": "#2b343d",
        "on-primary-container": "#95b9ff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#d9e4ef",
        "outline-variant": "#c3c6d2",
        "inverse-surface": "#213145"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "info-panel-width": "300px",
        "container-padding": "12px",
        "unit": "4px",
        "thread-list-width": "320px",
        "gutter": "16px",
        "sidebar-width": "240px"
      },
      fontFamily: {
        "jakarta": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "caption": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-lg": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-md": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "caption": ["10px", { lineHeight: "12px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}